config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  resources :staff_requests do 
    collection do
      get :autocomplete_for_name
      get :autocomplete_for_department_name
      get :autocomplete_for_boss_name
    end
  end
#  resources :staff_request_managers do
#    collection do
#      get :autocomplete_for_manager
#    end
#    member do
#      get :autocomplete_for_approver
#    end
#  end
end

app/models/staff_request.rb
class StaffRequest < ActiveRecord::Base
  unloadable

  belongs_to :issue, dependent: :destroy
  has_one :status, through: :issue
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :boss, class_name: 'User', foreign_key: 'boss_id'
  belongs_to :priority, class_name: 'IssuePriority', foreign_key: 'priority_id'

  validates_presence_of :name, :author_id, :company_name, :department_name,
    :boss_id, :position_type_name, :employment_type_name, :require_education_name,
    :priority_id, :position_count, :require_program_skills,
    :functional_responsibilities

  before_create :add_issue
  before_update :add_issue, if: -> { self.issue.blank? }
  after_create :add_approval_item

  scope :visible, lambda{
    if !User.current.admin? && !User.current.staff_manager?

      watchers_condition  = "#{self.table_name}.issue_id IN (select watchable_id from watchers where watchable_type='Issue' and user_id= ?)"
      approvers_condition = "#{self.table_name}.issue_id IN (select issue_id from approval_items where user_id= ?)"

      where("#{self.table_name}.author_id = ? OR #{watchers_condition} OR #{approvers_condition}", User.current.id, User.current.id, User.current.id)
    end
  }

  scope :issue_status, lambda {|q|
    if q.present?
      {:conditions =>
        ["#{self.table_name}.issue_id IN (SELECT #{Issue.table_name}.id FROM #{Issue.table_name} WHERE status_id=:status_id)",
        {:status_id => q}]}
    end
  }

  scope :issue_priority, lambda {|q|
    if q.present?
      {:conditions =>
        ["#{self.table_name}.issue_id IN (SELECT #{Issue.table_name}.id FROM #{Issue.table_name} WHERE priority_id=:priority_id)",
        {:priority_id => q}]}
    end
  }

  scope :like_field, lambda {|q, field|
    if q.present?
      {:conditions =>
        ["LOWER(#{field}) LIKE LOWER(?)", "%#{q.to_s.downcase}%"]}
    end
  }

  scope :eql_field, lambda {|q, field|
    if q.present? && field.present?
      where(field => q)
    end
  }

  def add_issue
    setting = Setting[:plugin_redmine_staff_request]
    self.create_issue(
      status: IssueStatus.default,
      tracker_id: setting[:tracker_id],
      project_id: setting[:project_id],
      assigned_to_id: setting[:assigned_to_id],
      author: User.current,
      start_date: Date.today,
      due_date: Date.today + setting[:duration].to_i.days,
      priority_id: self.priority_id,
      subject: ::I18n.t('message_staff_request_subject', :name => self.name, :position_count => self.position_count),
      description: [:company_name, :department_name, :boss_name, :position_type_name,
        :position_type_comment, :employment_type_name, :require_education_name].map do |item|
          "*#{::I18n.t('field_' + item.to_s, :default => item.to_s.humanize)}:* #{self.send(item)}" if self.send(item).present?
        end.compact.join("\n") + "\n\n" +
        [:require_program_skills, :functional_responsibilities].map do |item|
          "*#{::I18n.t('field_' + item.to_s, :default => item.to_s.humanize)}:*\n#{self.send(item)}" if self.send(item).present?
        end.join("\n\n"),
      #is_private: true
    )
  end

  def add_approval_item
    ApprovalItem.create(issue_id: self.issue_id, user_id: self.boss_id)
  rescue
  end

end

app/controllers/staff_requests_controller.rb
class StaffRequestsController < ApplicationController
  unloadable

  helper :journals
  helper :issues
  helper :sort
  include SortHelper
  helper :custom_fields
  include CustomFieldsHelper

  before_filter :require_staff_request_manager
  before_filter :find_object, :only => [:edit, :update, :show, :destroy]
  before_filter :new_object, :only => [:index, :new, :create]

  def index
    sort_init 'created_on', 'desc'
    sort_update %w(name company_name department_name boss_name position_type_name employment_type_name require_education_name created_on)

    @limit = per_page_option

    @scope = object_class_name.
      visible.
      issue_status(params[:status_id]).
      issue_priority(params[:priority_id]).
      like_field(params[:name], :name).
      like_field(params[:department_name], :department_name).
#      like_field(params[:boss_name], :boss_name).
      eql_field(params[:boss_id], :boss_id).
      eql_field(params[:company_name], :company_name).
      eql_field(params[:position_type_name], :position_type_name).
      eql_field(params[:employment_type_name], :employment_type_name).
      eql_field(params[:require_education_name], :require_education_name).
      eql_field(params[:created_on], :created_on).
      eql_field(params[:author_id], :author_id).
      time_period(params[:time_period_created_on], :created_on)

    @count = @scope.count
    @pages = Paginator.new(self, @count, @limit, params[:page])
    @offset ||= @pages.current.offset
    @collection = @scope.limit(@limit).offset(@offset).order(sort_clause).all
  end

  def create
    @object.author_id = User.current.id
    if @object.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => :show, :id => @object.id
    else
      render :action => :new
    end
  end

  def update
    if @object.update_attributes(params[object_sym])
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => :show, :id => @object.id
    else
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] = l(:notice_successful_delete) if @object.destroy
    redirect_to :action => :index
  end

  def show
    if @issue = @object.issue
      @journals = get_journals
    end
  end

  def autocomplete_for_name
    autocomplete_for_field(:name)
  end

  def autocomplete_for_department_name
    autocomplete_for_field(:department_name)
  end


  def autocomplete_for_boss_name
    autocomplete_for_field(:boss_name)
  end


  private
    def object_class_name
      StaffRequest
    end

    def object_sym
      :staff_request
    end

    def find_object
      @object = object_class_name.visible.find(params[:id])
    end

    def new_object
      @object = object_class_name.new(params[object_sym])
    end

    def get_journals
      journals = @issue.journals.includes(:user, :details).reorder("#{Journal.table_name}.id ASC").all
      journals.each_with_index {|j,i| j.indice = i+1}
      journals.reject!(&:private_notes?) unless User.current.allowed_to?(:view_private_notes, @issue.project)
      journals.reverse! if User.current.wants_comments_in_reverse_order?
      journals
    end

    def require_staff_request_manager
      (render_403; return false) unless User.current.staff_request_manager?
    end

    def autocomplete_for_field(field)
      completions = StaffRequest.where("#{field} LIKE ?", "#{params[:term]}%").
        order(field).
        uniq.
        limit(10).
        map{|l| { 'id' => l.id, 'label' => l.send(field), 'value' => l.send(field)} }
      render :text => completions.to_json, :layout => false
    end

end

app/helpers/staff_requests_helper.rb
module StaffRequestsHelper
  def company_name_for_select
    t(:company_name, scope: :staff_requiest)
  end

  def position_type_name_for_select
    t(:position_type_name, scope: :staff_requiest)
  end

  def employment_type_name_for_select
    t(:employment_type_name, scope: :staff_requiest)
  end

  def require_education_name_for_select
    t(:require_education_name, scope: :staff_requiest)
  end

  def status_id_for_select
    IssueStatus.order(:position)
  end

  def priority_id_for_select
    IssuePriority.order(:position)
  end

  def boss_id_for_select
    User.active.order(:lastname, :firstname)
  end

  def time_periods
    %w{yesterday last_week this_week last_month this_month last_year this_year}
  end

  def author_id_for_select
    User.where("#{User.table_name}.id IN (SELECT #{StaffRequest.table_name}.author_id FROM #{StaffRequest.table_name})").order(:lastname, :firstname)
  end
end

app/views/staff_requests/_filters.html.haml
:css
  .inline-block{ display: inline-block }

%fieldset
  %legend= l(:label_filter_plural)

  %form{:method => :get}
    - [:name, :department_name].each do |item|
      = hidden_field_tag item, params[item]

    .inline-block
      %label{:for=>'company_name'}= l(:field_company_name) + ":"
      %select{:id => 'company_name', :name => 'company_name', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        - company_name_for_select.each do |item|
          - if params[:company_name] == item
            %option{:value => item, :selected => "selected"}= item
          - else
            %option{:value => item}= item

    .inline-block
      %label{for: 'boss_id'}= l(:field_boss) + ":"
      %select{id: 'boss_id', name: 'boss_id', class: "small", onchange: "this.form.submit(); return false;"}
        %option
        = options_from_collection_for_select(boss_id_for_select, :id, :name, params[:boss_id] && params[:boss_id].to_i)

    .inline-block
      %label{:for=>'position_type_name'}= l(:field_position_type_name) + ":"
      %select{:id => 'position_type_name', :name => 'position_type_name', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        - position_type_name_for_select.each do |item|
          - if params[:position_type_name] == item
            %option{:value => item, :selected => "selected"}= item
          - else
            %option{:value => item}= item

    .inline-block
      %label{:for=>'employment_type_name'}= l(:field_employment_type_name) + ":"
      %select{:id => 'employment_type_name', :name => 'employment_type_name', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        - employment_type_name_for_select.each do |item|
          - if params[:employment_type_name] == item
            %option{:value => item, :selected => "selected"}= item
          - else
            %option{:value => item}= item

    .inline-block
      %label{:for=>'require_education_name'}= l(:field_require_education_name) + ":"
      %select{:id => 'require_education_name', :name => 'require_education_name', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        - require_education_name_for_select.each do |item|
          - if params[:require_education_name] == item
            %option{:value => item, :selected => "selected"}= item
          - else
            %option{:value => item}= item

    .inline-block
      %label{:for=>'status_id'}= l(:field_status) + ":"
      %select{:id => 'status_id', :name => 'status_id', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        = options_from_collection_for_select(status_id_for_select, :id, :name, params[:status_id] && params[:status_id].to_i)

    .inline-block
      %label{:for=>'priority_id'}= l(:field_priority) + ":"
      %select{:id => 'priority_id', :name => 'priority_id', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        = options_from_collection_for_select(priority_id_for_select, :id, :name, params[:priority_id] && params[:priority_id].to_i)

    .inline-block
      %label{:for=>'author_id'}= l(:field_author) + ":"
      %select{:id => 'author_id', :name => 'author_id', :class => "small", :onchange => "this.form.submit(); return false;"}
        %option
        = options_from_collection_for_select(author_id_for_select, :id, :name, params[:author_id] && params[:author_id].to_i)

    - %w{created_on}.each do |type_date|
      %br
      %label=l(:"label_period") + ":"
      -# - %w{all}.each do |key|
      -#   - if params[:"time_period_#{type_date}"] == key
      -#     %strong
      -#       = l(:"label_#{key}")
      -#   - else
      -#     = link_to l(:"label_#{key}"), params.merge( :"time_period_#{type_date}" => key, :"#{type_date}" => "" )

      -# = "/"
      %input{:id => type_date, :name => type_date, :size => 10, :onchange => "this.form.submit(); return false;", :value => params[type_date]}
      = calendar_for(type_date)

      - StaffRequest.time_periods.each do |key|
        = "/"
        - if params[:"time_period_#{type_date}"] == key
          %strong
            = l(:"label_period_#{key}")
        - else
          = link_to l(:"label_period_#{key}"), params.merge( :"time_period_#{type_date}" => key, :"#{type_date}" => "" )
    %br

  %form{:method => :get}
    - [:boss_id,:company_name,:position_type_name,:employment_type_name,:require_education_name,:status_id,:priority_id,:author_id,:time_period_created_on].each do |item|
      = hidden_field_tag item, params[item]

    %label{:for=>'name'}= l(:label_staff_request_name) + ":"
    = text_field_tag 'name', params[:name], :size => 30

    %label{:for=>'department_name'}= l(:field_department_name) + ":"
    = text_field_tag 'department_name', params[:department_name], :size => 30

    = submit_tag l(:button_apply), :class => "small", :name => nil
    = link_to l(:button_clear), {:action => :index}, :class => 'icon icon-reload'

app/views/staff_requests/_form.html.haml
= error_messages_for @object

.box.tabular
  .splitcontentleft
    %p= f.select :company_name, company_name_for_select, required: true, include_blank: t(:prompt_please_select)

    %p= f.text_field :department_name, required: true, size: 40
    :javascript
      observeAutocompleteField('staff_request_department_name', '#{escape_javascript autocomplete_for_department_name_staff_requests_path}')

    %p= f.text_field :name, required: true, size: 40, label: t(:label_staff_request_name)
    :javascript
      observeAutocompleteField('staff_request_name', '#{escape_javascript autocomplete_for_name_staff_requests_path}')

    %p
      = f.select :boss_id, boss_id_for_select.map{ |item| [item.name, item.id] }, required: true, include_blank: t(:prompt_please_select)
      = h @object.boss_name

    %p= f.text_field :position_count, required: true, size: 5

  .splitcontentright
    %p= f.select :position_type_name, position_type_name_for_select, required: true, include_blank: t(:prompt_please_select)
    %p= f.text_field :position_type_comment, size: 20
    %p= f.select :employment_type_name, employment_type_name_for_select, required: true, include_blank: t(:prompt_please_select)
    %p= f.select :require_education_name, require_education_name_for_select, required: true, include_blank: t(:prompt_please_select)
    %p= f.select :priority_id, priority_id_for_select.map{ |item| [item.name, item.id] }, required: true, include_blank: t(:prompt_please_select)

  %div{:style=>"clear:both"}

  %p= f.text_area :require_program_skills,      cols: 60, rows: 15, class: 'wiki-edit', required: true
  %p= f.text_area :functional_responsibilities, cols: 60, rows: 15, class: 'wiki-edit', required: true

= wikitoolbar_for 'staff_request_require_program_skills'
= wikitoolbar_for 'staff_request_functional_responsibilities'

app/views/staff_requests/_settings.html.haml
%p
  %label= l(:label_staff_request_manager_plural)
  = select_tag("settings[principal_id]", principals_options_for_select(Principal.active.all, (Principal.find(@settings[:principal_id]) rescue nil)), :prompt => t(:prompt_please_select))
%p
  %label= l(:label_project)
  = select_tag("settings[project_id]", project_tree_options_for_select(Project.active.all, :selected => (Project.find(@settings[:project_id]) rescue nil)), :prompt => t(:prompt_please_select))
%p
  %label= l(:label_tracker)
  = select_tag("settings[tracker_id]", options_from_collection_for_select(Tracker.all, :id, :name, (@settings[:tracker_id].try(:to_i))), :prompt => t(:prompt_please_select))
%p
  %label= l(:label_duration)
  = text_field_tag("settings[duration]", @settings[:duration], :size => 5)
%p
  %label= l(:label_assigned_to)
  = select_tag("settings[assigned_to_id]", principals_options_for_select(Principal.active.all(:order => [:lastname, :firstname]), (Principal.find(@settings[:assigned_to_id]) rescue nil)), :prompt => t(:prompt_please_select))

app/views/staff_requests/edit.html.haml
%h2= l(:label_edit_staff_request)

= labelled_form_for @object, :html => {:method => :put} do |f|
  = render :partial => 'form', :locals => { :f => f }
  = submit_tag l(:button_save)

app/views/staff_requests/index.html.haml
.contextual
  = link_to l(:label_staff_request_new), {:action => :new}, :class => 'icon icon-add'

%h2=l(:label_staff_request_plural)
- html_title l(:label_staff_request_plural)

= render :partial => 'filters'

- if @collection.any?
  .autoscroll
    %table.list
      %thead
        %tr
          %th= "#"
          %th= l(:label_issue_status)
          = sort_header_tag 'name', :caption => l(:label_staff_request_name)
          = sort_header_tag 'company_name', :caption => l(:field_company_name)
          = sort_header_tag 'department_name', :caption => l(:field_department_name)
          = sort_header_tag 'boss_name', :caption => l(:field_boss_name)
          = sort_header_tag 'position_type_name', :caption => l(:field_position_type_name)
          = sort_header_tag 'employment_type_name', :caption => l(:field_employment_type_name)
          = sort_header_tag 'require_education_name', :caption => l(:field_require_education_name)
          %th= l(:field_priority)
          %th= l(:field_author)
          = sort_header_tag 'created_on', :caption => l(:field_created_on)
          %th
      %tbody
        - @collection.each do |item|
          %tr{:class=>cycle("odd", "even")}
            %td{:align=>"center"}
              - if item.issue.present?
                = link_to "##{item.issue.id}", controller: 'issues', action: 'show', id: item.issue.id
            %td{:align=>"center"}= h(item.status)
            %td{:align=>"left"}= link_to h("#{item.name} (#{item.position_count})"), :action => :show, :id => item.id
            %td{:align=>"center"}= h(item.company_name)
            %td{:align=>"center"}= h(item.department_name)
            %td{:align=>"center"}= link_to_user item.boss
            %td{:align=>"center"}= h(item.position_type_name)
            %td{:align=>"center"}= h(item.employment_type_name)
            %td{:align=>"center"}= h(item.require_education_name)
            %td{:align=>"center"}= h(item.priority)
            %td{:align=>"center"}= link_to item.author, params.merge(:author_id => item.author_id)
            %td{:align=>"center"}= format_date(item.created_on)
            %td.buttons
              - if item.author == User.current || User.current.admin?
                = link_to l(:button_update), {:action => :edit, :id => item.id}, :class => 'icon icon-edit'
                = link_to(l(:button_delete), {:action => :destroy, :id => item.id}, :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del')

  %p.pagination= pagination_links_full @pages, @count
- else
  %p.nodata
    = l(:label_no_data)

app/views/staff_requests/new.html.haml
%h2
  = link_to l(:label_staff_request_plural), :action => :index
  &#187;
  = l(:label_new_staff_request)

= labelled_form_for @object, :url => {:action => :create} do |f|
  = render :partial => 'form', :locals => { :f => f }
  = submit_tag l(:button_create)
  = submit_tag l(:button_create_and_continue), :name => 'continue'

app/views/staff_requests/show.html.haml
.contextual
  = link_to l(:button_add), {:action => :new}, :class => 'icon icon-add'
  = link_to l(:button_update), {:action => :edit, :id => @object}, :class => 'icon icon-edit'
  = link_to l(:button_delete), {:action => :destroy, :id => @object}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del'

%h2
  = link_to l(:label_staff_request), :action => :index
  &#187;
  = h(@object.name)
  = "(#{@object.position_count})"

.issue.details
  %table.attributes
    %tr
      %th= l(:field_company_name)+":"
      %td= h(@object.company_name)
      %th= l(:field_position_type_name)+":"
      %td= h(@object.position_type_name)
    %tr
      %th= l(:field_department_name)+":"
      %td= h(@object.department_name)
      %th= l(:field_position_type_comment)+":"
      %td= h(@object.position_type_comment)
    %tr
      %th= l(:field_boss_name)+":"
      %td= h(@object.boss_name)
      %th= l(:field_employment_type_name)+":"
      %td= h(@object.employment_type_name)
    %tr
      %th= l(:field_priority)+":"
      %td= h(@object.priority.try(:name))
      %th= l(:field_require_education_name)+":"
      %td= h(@object.require_education_name)
    %tr
      %th= l(:field_created_on)+":"
      %td= format_date(@object.created_on)
      %th= l(:field_author)+":"
      %td= link_to_user @object.author
    %tr
      %th= l(:field_issue)+":"
      %td{colspan: 3}
        - if @object.issue.present?
          = link_to_issue @object.issue, project: false, subject: false, tracker: false
  %hr
  %p
    %strong= l(:field_require_program_skills)
  .wiki= textilizable @object, :require_program_skills
  %p
    %strong= l(:field_functional_responsibilities)
  .wiki= textilizable @object, :functional_responsibilities

- if @journals.present?
  #history
    = render :partial => 'issues/history', :locals => { :issue => @issue, :journals => @journals }